services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: digiuser
      POSTGRES_PASSWORD: qniCrDWiPa
      POSTGRES_DB: digipocket
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
       - "5435:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3031:3031"
    env_file:
      - ./backend/env.docker
    depends_on:
      - db
      - redis

  # Background workers (ใช้ภาพเดียวกับ backend) ---------------------------------

  deposit_worker:
    build: ./backend
    command: bun run src/workers/deposit.worker.ts
    restart: unless-stopped
    env_file:
      - ./backend/env.docker
    depends_on:
      - db
      - redis

  peamsub_worker:
    build: ./backend
    command: bun run src/workers/peamsub.worker.ts
    restart: unless-stopped
    env_file:
      - ./backend/env.docker
    depends_on:
      - db
      - redis

  product_sync:
    build: ./backend
    command: bun run src/workers/product-sync.worker.ts
    restart: unless-stopped
    env_file:
      - ./backend/env.docker
    depends_on:
      - db
      - redis

  prune_prices:
    build: ./backend
    command: bun run src/workers/prune-prices.worker.ts
    restart: unless-stopped
    env_file:
      - ./backend/env.docker
    depends_on:
      - db
      - redis

  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    ports:
      - "8085:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://digiuser:qniCrDWiPa@db:5432/digipocket?sslmode=disable
    depends_on:
      - db

volumes:
  postgres-data:
  redis-data: 